# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/mt6757-common/setup-makefiles.sh

V := vendor/sony/mt6757-common
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,$(V)/bin,system/bin) $(call find-copy-subdir-files,*,$(V)/etc,system/etc) $(call find-copy-subdir-files,*,$(V)/lib,system/lib) $(call find-copy-subdir-files,*,$(V)/lib64,system/lib64) $(call find-copy-subdir-files,*,$(V)/vendor,$(TARGET_COPY_OUT_VENDOR))
